import { TanstackQueryProvider, ToastProvider } from "@/providers";
import WagmiProvider from "@/providers/wagmi/Wagmi.provider";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Didik NVP Test",
  description: "Generated by create next app",
};

/**
 * Root layout component that wraps the entire application.
 *
 * This component sets up the HTML structure and applies global styles
 * and theme provider. It uses local fonts and passes down the children
 * components within the <body> tag.
 *
 * @param {Object} props - Component properties.
 * @param {React.ReactNode} props.children - The child components to be rendered
 * within the layout.
 *
 * @returns {JSX.Element} A JSX element representing the root layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class">
          <WagmiProvider>
            <TanstackQueryProvider>
              <ToastProvider>{children}</ToastProvider>
            </TanstackQueryProvider>
          </WagmiProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
